// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"","parentId":"@@/global-layout","id":"1"},"2":{"path":"/condition","parentId":"@@/global-layout","id":"2"},"@@/global-layout":{"id":"@@/global-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import(/* webpackChunkName: "p__monaco" */'@/pages/monaco.tsx')),
'2': React.lazy(() => import(/* webpackChunkName: "p__condition" */'@/pages/condition.tsx')),
'@@/global-layout': React.lazy(() => import(/* webpackChunkName: "layouts__index" */'/Users/gaoxin/Documents/项目/umi/src/layouts/index.tsx')),
},
  };
}
